package org.example.project

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Semantic colours shared across ArthoCare. The **dark** palette preserves every
 * hex value from the legacy [AppDark] object; the **light** palette follows the
 * clinical spec in the product brief.
 */
data class AppColorTokens(
    val gradientTop: Color,
    val gradientBottom: Color,
    val chromeSurface: Color,
    val chromeOnSurfaceMuted: Color,
    val heroSurface: Color,
    val cardSurface: Color,
    val heroBorder: Color,
    val cardBorder: Color,
    val primaryButton: Color,
    val linkAccent: Color,
    val sectionHighlight: Color,
    val onAccent: Color,
    val onSurfaceStrong: Color,
    val onSurfaceSecondary: Color,
    val onSurfaceMuted: Color,
    val onSurfaceFaint: Color,
    val warningSurface: Color,
    val warningBorder: Color,
    val riskLow: Color,
    val riskModerate: Color,
    val riskHigh: Color,
    val inputFill: Color,
    val accentContainer: Color,
    val onAccentContainer: Color,
    val divider: Color,
    val chartSeries1: Color,
    val chartSeries2: Color,
    val chartSeries3: Color,
    val materialError: Color,
    val materialOnError: Color,
    val materialErrorContainer: Color,
    val materialOnErrorContainer: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
)

object AppPalettes {
    /** Exact legacy dark palette — values must not drift from the original AppDark object. */
    val dark = AppColorTokens(
        gradientTop = Color(0xFF1A1025),
        gradientBottom = Color(0xFF0D0B12),
        chromeSurface = Color(0xFF110E1A),
        chromeOnSurfaceMuted = Color.White.copy(alpha = 0.55f),
        heroSurface = Color(0xFF2A1F3D),
        cardSurface = Color(0xFF1E1630),
        heroBorder = Color(0xFF7B5EA7),
        cardBorder = Color(0xFF6B4FA0),
        primaryButton = Color(0xFF7B5EA7),
        linkAccent = Color(0xFFB08AFF),
        sectionHighlight = Color(0xFFCFB3FF),
        onAccent = Color.White,
        onSurfaceStrong = Color.White,
        onSurfaceSecondary = Color.White.copy(alpha = 0.78f),
        onSurfaceMuted = Color.White.copy(alpha = 0.6f),
        onSurfaceFaint = Color.White.copy(alpha = 0.4f),
        warningSurface = Color(0xFF5D1F1A),
        warningBorder = Color(0xFFE53935),
        riskLow = Color(0xFF4CAF50),
        riskModerate = Color(0xFFFF9800),
        riskHigh = Color(0xFFE53935),
        inputFill = Color(0xFF1E1630),
        accentContainer = Color(0xFF2A1F3D),
        onAccentContainer = Color(0xFFCFB3FF),
        divider = Color(0xFF6B4FA0).copy(alpha = 0.35f),
        chartSeries1 = Color(0xFFCFB3FF),
        chartSeries2 = Color(0xFF4EADEA),
        chartSeries3 = Color(0xFFF59E0B),
        materialError = Color(0xFFFF7A9A),
        materialOnError = Color.White,
        materialErrorContainer = Color(0xFF5D1F1A),
        materialOnErrorContainer = Color(0xFFFFAB91),
        surfaceVariant = Color(0xFF2A1F3D),
        onSurfaceVariant = Color(0xFFD9CFFF),
        outline = Color(0xFF6B4FA0).copy(alpha = 0.55f),
        outlineVariant = Color(0xFF6B4FA0).copy(alpha = 0.32f),
    )

    val light = AppColorTokens(
        gradientTop = Color(0xFFF5F5FA),
        gradientBottom = Color(0xFFF8F8FB),
        chromeSurface = Color(0xFFFFFFFF),
        chromeOnSurfaceMuted = Color(0xFF8888AA),
        heroSurface = Color(0xFFEDE8FF),
        cardSurface = Color(0xFFFFFFFF),
        heroBorder = Color(0xFF7B61FF).copy(alpha = 0.35f),
        cardBorder = Color(0xFFE0E0EC),
        primaryButton = Color(0xFF7B61FF),
        linkAccent = Color(0xFF7B61FF),
        sectionHighlight = Color(0xFF5B4ACF),
        onAccent = Color(0xFFFFFFFF),
        onSurfaceStrong = Color(0xFF1A1A2E),
        onSurfaceSecondary = Color(0xFF4A4A6A),
        onSurfaceMuted = Color(0xFF8888AA),
        onSurfaceFaint = Color(0xFF8888AA).copy(alpha = 0.55f),
        warningSurface = Color(0xFFFFF4E5),
        warningBorder = Color(0xFFD97706),
        riskLow = Color(0xFF1E8E5A),
        riskModerate = Color(0xFFD97706),
        riskHigh = Color(0xFFC0392B),
        inputFill = Color(0xFFEFEFEF),
        accentContainer = Color(0xFFEDE8FF),
        onAccentContainer = Color(0xFF3D2DB5),
        divider = Color(0xFFE0E0EC),
        chartSeries1 = Color(0xFF7B61FF),
        chartSeries2 = Color(0xFF4EADEA),
        chartSeries3 = Color(0xFFF59E0B),
        materialError = Color(0xFFC0392B),
        materialOnError = Color(0xFFFFFFFF),
        materialErrorContainer = Color(0xFFFFE5E5),
        materialOnErrorContainer = Color(0xFF7A1F18),
        surfaceVariant = Color(0xFFEFEFEF),
        onSurfaceVariant = Color(0xFF4A4A6A),
        outline = Color(0xFFE0E0EC),
        outlineVariant = Color(0xFFE0E0EC).copy(alpha = 0.6f),
    )
}

val LocalAppColors = staticCompositionLocalOf { AppPalettes.dark }

fun AppColorTokens.toMaterialColorScheme(isDark: Boolean): ColorScheme {
    return if (isDark) {
        darkColorScheme(
            primary = primaryButton,
            onPrimary = onAccent,
            primaryContainer = heroSurface,
            onPrimaryContainer = sectionHighlight,
            secondary = linkAccent,
            onSecondary = onAccent,
            secondaryContainer = cardSurface,
            onSecondaryContainer = sectionHighlight,
            tertiary = linkAccent,
            onTertiary = onAccent,
            tertiaryContainer = heroSurface,
            onTertiaryContainer = sectionHighlight,
            background = gradientBottom,
            onBackground = onSurfaceStrong,
            surface = cardSurface,
            onSurface = onSurfaceStrong,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            outline = outline,
            outlineVariant = outlineVariant,
            error = materialError,
            onError = materialOnError,
            errorContainer = materialErrorContainer,
            onErrorContainer = materialOnErrorContainer,
        )
    } else {
        lightColorScheme(
            primary = primaryButton,
            onPrimary = onAccent,
            primaryContainer = accentContainer,
            onPrimaryContainer = onAccentContainer,
            secondary = linkAccent,
            onSecondary = onAccent,
            secondaryContainer = accentContainer,
            onSecondaryContainer = onAccentContainer,
            tertiary = chartSeries2,
            onTertiary = onAccent,
            tertiaryContainer = surfaceVariant,
            onTertiaryContainer = onSurfaceStrong,
            background = gradientBottom,
            onBackground = onSurfaceStrong,
            surface = cardSurface,
            onSurface = onSurfaceStrong,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            outline = outline,
            outlineVariant = outlineVariant,
            error = materialError,
            onError = materialOnError,
            errorContainer = materialErrorContainer,
            onErrorContainer = materialOnErrorContainer,
        )
    }
}
